// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [
  //   // {type: 'autogenerated', dirName: '.'},
  //   {
  //     type: 'category',
  //     label: 'ROS 2 Nervous System Introduction',
  //     items: [
  //       'ros2-nervous-system/intro',
  //       'ros2-nervous-system/nodes',
  //       'ros2-nervous-system/topics',
  //       'ros2-nervous-system/services',
  //       'ros2-nervous-system/urdf',
  //       'ros2-nervous-system/architecture',
  //       'ros2-nervous-system/hello-world-tutorial',
  //       'ros2-nervous-system/prerequisites',
  //       'ros2-nervous-system/troubleshooting',
  //       'ros2-nervous-system/summary',
  //     ],
  //   },
  // ],
 tutorialSidebar: [
    
    // ---------------------------------------------
    // Main Heading 1: Foundation and Core Concepts
    {
      type: 'category',
      label: 'I. ROS 2 Foundation & Core', // <-- Aapki Pehli Top-Level Heading
      collapsible: true,
      collapsed: false, 
      items: [
        'ros2-nervous-system/intro',
        'ros2-nervous-system/prerequisites',
        'ros2-nervous-system/nodes',
        'ros2-nervous-system/topics',
        'ros2-nervous-system/services',
        'ros2-nervous-system/urdf',
        'ros2-nervous-system/architecture',
      ],
    },
    
    // ---------------------------------------------
    // Main Heading 2: Practical Implementation (Lab Exercise)
    {
      type: 'category',
      label: '2. Practical Implementation (Lab)', // <-- Aapki Doosri Top-Level Heading
      collapsible: true,
      collapsed: false,
      items: [
        'ros2-nervous-system/hello-world-tutorial', // Main code task
      ],
    },
    
    // ---------------------------------------------
    // Main Heading 3: Debugging and Conclusion
    {
      type: 'category',
      label: '3. Debugging & Summary', // <-- Aapki Teesri Top-Level Heading
      collapsible: true,
      collapsed: false,
      items: [
        'ros2-nervous-system/troubleshooting',
        'ros2-nervous-system/summary',
      ],
    },
    // ---------------------------------------------
  ],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
